GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE http://localhost:3001/todo/delete/64e1ad4c63f8df16e938ccad

###

PUT http://localhost:3001/todo/complete/64e073909c31b1b48e82e834