GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE http://localhost:3001/todo/delete/64e1ad4c63f8df16e938ccad

###

PUT http://localhost:3001/todo/complete/64e0d1b7df4ff8e4b285e610